dist: xenial
language: python
python:
  - "3.7"

services:
  - docker

branches:
  only:
  - master
  
install:
  - pip install -r requirements.txt
  - pip install codecov

script: 
  - make build
  - coverage run manage.py test
  - codecov
  
deploy:
  provider: script
  script: bash docker-push.sh
  on:
    branch: master
  
