dist: xenial
language: python
python:
  - "3.7"

services:
  - docker

branches:
  only:
  - master
  
install:
  - pip install -r requirements.txt
  - pip install codecov

script: 
  - make build
  - coverage run manage.py test
  - bash docker-push.sh

after_success:
- bash < (curl -s https://codecov.io/bash)