dist: xenial
language: python
python:
  - "3.7"

services:
  - docker
addons:
  chrome: stable
  
branches:
  only:
  - master

install:
  - pip install -r requirements.txt

before_script:
  - wget https://chromedriver.storage.googleapis.com/73.0.3683.68/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.7.1/bin/
  - export CHROME_BIN=chromium-browser

script: 
  - make build
  - bash docker-push.sh
