dist: xenial
language: python
python:
  - "3.7"

services:
  - docker

install:
  - pip install -r requirements.txt

script: 
  - make build

after_success:
  - docker build . -t en-cas-de-soif:latest
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push loicrosso/en-cas-de-soif:latest
