dist: xenial
sudo: required
language: python
python:
  - "3.7"

services:
  - docker
  - xvfb
addons:
  chrome: stable
  
branches:
  only:
  - master

before_install:
  - wget https://chromedriver.storage.googleapis.com/73.0.3683.68/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /usr/bin/
  - export CHROME_BIN=chromium-browser

install:
  - pip install -r requirements.txt


script: 
  - make build
  - bash docker-push.sh
