dist: xenial
language: python
python:
  - "3.7"

services:
  - docker
addons:
  chrome: stable
  
branches:
  only:
  - master

before_install:
  - wget https://chromedriver.storage.googleapis.com/73.0.3683.68/chromedriver_linux64.zip
  - sudo unzip chromedriver_linux64.zip -d /usr/bin/
  - export CHROME_BIN=chromium-browser

install:
  - pip install -r requirements.txt

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  - make build
  - bash docker-push.sh
